set(FREERTOS_PORT "XCOREAI")

add_compile_definitions(
    XCOREAI_EXPLORER=1
    PLATFORM_SUPPORTS_TILE_0=1
    PLATFORM_SUPPORTS_TILE_1=1
    PLATFORM_SUPPORTS_TILE_2=0
    PLATFORM_SUPPORTS_TILE_3=0
)
