#!/usr/bin/env bash

function trace_help() {
    echo "Options:"
    echo "--clean         : Delete temporary files generated by this script"
    echo "--convert / -c  : Convert xscope output file to SysView format"
    echo "--help    / -h  : Display help information"
    echo "--run     / -r  : Build and run demo"
    echo "--test    / -t  : Convert xscope output and open files in SysView"
    echo "--ascii   / -a  : Convert xscope output to ascii"
    echo "--view    / -v  : View files in SysView"
    return
}

function trace_run() {
    xwaf distclean configure build && xrun --xscope-file tmp_trace/xscope_sysview.txt bin/Default/app_freertos_ethernet_Default.xe
}

function trace_test() {
    python ../../../FreeRTOS/FreeRTOSv10.2.1/FreeRTOS/Python/xtrace_sysview.py tmp_trace/xscope_sysview.txt -output_file=tmp_trace/trace_output -xscope=config.xscope --package=XS200_SLICE_2TILE
    echo "Only opens a new instance of SysView.  Does not open all 32 files."
    SystemView > tmp_trace/tmp &
}

function trace_convert() {
    python ../../../FreeRTOS/FreeRTOSv10.2.1/FreeRTOS/Python/xtrace_sysview.py tmp_trace/xscope_sysview.txt -output_file=tmp_trace/trace_output --package=XS200_SLICE_2TILE
}

function trace_view() {
    echo "Only opens a new instance of SysView.  Does not open all 32 files."
    SystemView > tmp_trace/tmp &
}

function trace_ascii() {
    python ../../../FreeRTOS/FreeRTOSv10.2.1/FreeRTOS/Python/xtrace_ascii.py tmp_trace/xscope_sysview.txt -xscope=config.xscope -mode=text -output_file=tmp_trace/trace_output -config_file=../../../FreeRTOS/FreeRTOSv10.2.1/FreeRTOS/Python/trace_show.json --show_by=core --package=XS200_SLICE_2TILE 
}

function trace_clean() {
    rm tmp_trace -r
}

if [ ! -d "tmp_trace" ]; then
  mkdir tmp_trace
fi

if [ $# == 1 ]
then
    if [ "$1" == "--help" ] || [ "$1" == "-h" ]
    then
        trace_help
    elif [ "$1" == "--run" ] || [ "$1" == "-r" ]
    then
        trace_run
    elif [ "$1" == "--test" ] || [ "$1" == "-t" ]
    then
        trace_test
    elif [ "$1" == "--convert" ] || [ "$1" == "-c" ]
    then
        trace_convert
    elif [ "$1" == "--view" ] || [ "$1" == "-v" ]
    then
        trace_view
    elif [ "$1" == "--ascii" ] || [ "$1" == "-a" ]
    then
        trace_ascii
    elif [ "$1" == "--clean" ]
    then
        trace_clean
    fi
else
    echo "Error! --help or -h for help"
fi



