def options(opt):
    opt.load('xwaf.xcommon')

def configure(conf):
    conf.load('xwaf.xcommon')

def build(bld):
    bld.do_xcommon()

def dist(ctx):
    ctx.load('xwaf.xcommon')

def distcheck(ctx):
    ctx.load('xwaf.xcommon')
