// Copyright (c) 2019, XMOS Ltd, All rights reserved

#ifndef MICARRAY_DEV_CONF_DEFAULTS_H_
#define MICARRAY_DEV_CONF_DEFAULTS_H_

/* 32 bit samples if 0, 16 if 1 */
#ifndef MICARRAYCONF_WORD_LENGTH_SHORT
#define MICARRAYCONF_WORD_LENGTH_SHORT      (0)
#endif

/* Indicates size of frames coming from decimator */
#ifndef MICARRAYCONF_MAX_FRAME_SIZE_LOG2
#define MICARRAYCONF_MAX_FRAME_SIZE_LOG2    (8)
#endif

#ifndef MICARRAYCONF_NUM_MICS
#define MICARRAYCONF_NUM_MICS               (4)
#endif

#ifndef MICARRAYCONF_DECIMATOR_COUNT
#define MICARRAYCONF_DECIMATOR_COUNT        (1)
#endif

#ifndef MICARRAYCONF_NUM_FRAME_BUFFERS
#define MICARRAYCONF_NUM_FRAME_BUFFERS      (2)
#endif

#ifndef MICARRAYCONF_PDM_INTEGRATION_FACTOR
#define MICARRAYCONF_PDM_INTEGRATION_FACTOR (32)
#endif

#ifndef MICARRAYCONF_SAMPLE_RATE
#define MICARRAYCONF_SAMPLE_RATE            (48000)
#endif

#ifndef MICARRAYCONF_MASTER_TO_PDM_CLOCK_DIVIDER
#define MICARRAYCONF_MASTER_TO_PDM_CLOCK_DIVIDER    (8)
#endif

#ifndef MICARRAYCONF_MASTER_CLOCK_FREQUENCY
#define MICARRAYCONF_MASTER_CLOCK_FREQUENCY (24576000)
#endif

#endif /* MICARRAY_DEV_CONF_DEFAULTS_H_ */
