/*
 * xcore_freertos_conf.h
 *
 *  Created on: Oct 1, 2019
 *      Author: jmccarthy
 */


#ifndef SOC_CONF_H_
#define SOC_CONF_H_

#define XCORE_FREERTOS_MULTITILE        1
#define XCORE_FREERTOS_TILE_0_INCLUDE   XCORE_FREERTOS_TILE_HAS_BOTH
#define XCORE_FREERTOS_TILE_1_INCLUDE   XCORE_FREERTOS_TILE_HAS_BITSTREAM
#define XCORE_FREERTOS_TILE_2_INCLUDE   XCORE_FREERTOS_TILE_UNUSED
#define XCORE_FREERTOS_TILE_3_INCLUDE   XCORE_FREERTOS_TILE_UNUSED

#endif /* SOC_CONF_H_ */
