/*
 * xcore_freertos_conf_defaults.h
 *
 *  Created on: Sep 24, 2019
 *      Author: mbruno
 */


#ifndef SOC_CONF_DEFAULTS_H_
#define SOC_CONF_DEFAULTS_H_

#ifndef XCORE_FREERTOS_TILE_0_INCLUDE
#define XCORE_FREERTOS_TILE_0_INCLUDE XCORE_FREERTOS_TILE_HAS_SOFTWARE
#endif

#ifndef XCORE_FREERTOS_TILE_1_INCLUDE
#define XCORE_FREERTOS_TILE_1_INCLUDE XCORE_FREERTOS_TILE_UNUSED
#endif

#ifndef XCORE_FREERTOS_TILE_2_INCLUDE
#define XCORE_FREERTOS_TILE_2_INCLUDE XCORE_FREERTOS_TILE_UNUSED
#endif

#ifndef XCORE_FREERTOS_TILE_3_INCLUDE
#define XCORE_FREERTOS_TILE_3_INCLUDE XCORE_FREERTOS_TILE_UNUSED
#endif



#endif /* SOC_CONF_DEFAULTS_H_ */
