# YAML schema for GitHub Actions:
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
#
# Helpful YAML parser to clarify YAML syntax:
# https://yaml-online-parser.appspot.com/
#
# This workflow uses actions that are not certified by GitHub. They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support documentation.
#
# This file contains the workflows that are run prior to merging a pull request.

name: AI Tools

on:
  # Allow manually triggering of the workflow.
  workflow_dispatch: {}

env:
  XCORE_SDK_PATH: ${{ github.workspace }}

jobs:
  install_and_test_ai_tools:
    name: Install and test AI Tools
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SDK
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Checkout AI Tools
        uses: actions/checkout@v2
        with:
          repository: xmos/ai_tools
          ref: 'cb81a22ba82a06a14dc210799589a24c00c2e24a'
          path: tools/ai/ai_tools
          submodules: recursive

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Pull xcore_sdk_builder container
        run: |
          docker pull ghcr.io/xmos/xcore_sdk_builder:develop 

      - name: Install
        run: |
          docker run --user $(id -u) --rm -w /xcore_sdk -e XCORE_SDK_PATH=/xcore_sdk -v ${{ github.workspace }}:/xcore_sdk ghcr.io/xmos/xcore_sdk_builder:develop bash -l tools/ai/install.sh

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/install/requirements.txt
          pip install -r tools/ai/requirements.txt
          
      - name: Test
        run: |
          cd test/ai && pytest -v test_tflite2xcore_install.py &&  && bash test_scripts.sh && bash test_notebooks.sh
