# YAML schema for GitHub Actions:
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
#
# Helpful YAML parser to clarify YAML syntax:
# https://yaml-online-parser.appspot.com/
#
# This workflow uses actions that are not certified by GitHub. They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support documentation.
#
# This file contains the workflows that are run prior to merging a pull request.

name: CI

on:
  push:
    branches:
      - 'main'
      - 'develop'
  pull_request:
    branches:
      - 'main'
      - 'develop'

  # Allow manually triggering of the workflow.
  workflow_dispatch: {}

env:
  SDK_BUILDER_IMAGE: 'ghcr.io/xmos/sdk_app_builder:develop'

jobs:
  build_host_apps:
    name: Build host applications
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Pull SDK builder
        run: |
          docker pull ${SDK_BUILDER_IMAGE}

      - name: Build
        run: |
          docker run --rm -w /xcore_sdk -v ${{github.workspace}}:/xcore_sdk ${SDK_BUILDER_IMAGE} bash -l tools/ci/build_host_apps.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: host_apps
          path: ./dist_host

  build_rtos_core_examples:
    name: Build RTOS core examples
    runs-on: ubuntu-latest
    needs: build_host_apps
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Pull SDK builder
        run: |
          docker pull ${SDK_BUILDER_IMAGE}

      - name: Download host build artifacts
        uses: actions/download-artifact@v3
        with:
          name: host_apps
          path: ./dist_host

      - name: Build
        run: |
          docker run --rm -w /xcore_sdk -v ${{github.workspace}}:/xcore_sdk ${SDK_BUILDER_IMAGE} bash -l tools/ci/build_rtos_core_examples.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: freertos_core_examples
          path: |
            ./dist/*.xe
            ./dist/*.fs
            ./dist/*.swmem

  build_rtos_aiot_examples:
    name: Build RTOS AIoT examples
    runs-on: ubuntu-latest
    needs: build_host_apps
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' 

      - name: Install Python requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/install/requirements.txt

      - name: Make input data for examples
        run: |
          cd ./examples/freertos/cifar10/filesystem_support/test_inputs && python make_test_tensors.py

      - name: Pull SDK builder
        run: |
          docker pull ${SDK_BUILDER_IMAGE}

      - name: Download host build artifacts
        uses: actions/download-artifact@v3
        with:
          name: host_apps
          path: ./dist_host

      - name: Build
        run: |
          docker run --rm -w /xcore_sdk -v ${{github.workspace}}:/xcore_sdk ${SDK_BUILDER_IMAGE} bash -l tools/ci/build_rtos_aiot_examples.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: freertos_aiot_examples
          path: |
            ./dist/*.xe
            ./dist/*.fs
            ./dist/*.swmem

  build_metal_examples:
    name: Build bare-metal examples
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Pull SDK builder
        run: |
          docker pull ${SDK_BUILDER_IMAGE}

      - name: Build
        run: |
          docker run --rm -w /xcore_sdk -v ${{github.workspace}}:/xcore_sdk ${SDK_BUILDER_IMAGE} bash -l tools/ci/build_metal_examples.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bare-metal_examples
          path: ./dist/*.xe