# YAML schema for GitHub Actions:
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
#
# Helpful YAML parser to clarify YAML syntax:
# https://yaml-online-parser.appspot.com/
#
# This workflow uses actions that are not certified by GitHub. They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support documentation.
#
# This file contains the workflows that are run prior to merging a pull request.

name: Nightly

on:
  schedule:
    # 0am UTC is 5am or 4am ET depending on daylight savings.
    - cron: '0 0 * * *'

  # Allow manually triggering of the workflow.
  workflow_dispatch: {}

env:
  XCORE_SDK_PATH: ${{ github.workspace }}

jobs:
  build:
    name: Build examples
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'schedule' && github.repository == 'xmos/xcore_sdk')
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          echo "TODO: Build stuff!"
